[package]
name = "smallvec"
version = "0.1.5"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
license = "MPL-2.0"
repository = "https://github.com/servo/rust-smallvec"
description = "'Small vector' optimization: store up to a small number of items on the stack"
readme = "README.md"
documentation = "http://doc.servo.org/smallvec/"

[lib]
name = "smallvec"
path = "lib.rs"
doctest = false
